config/routes.rb
Rails.application.routes.draw do
  root 'plates#index'
  post "detective" => "plates#detective"
  resources :plates
  resources :blacklists
end

app/models/blacklist.rb
class Blacklist < ActiveRecord::Base
end

app/models/plate.rb
class Plate < ActiveRecord::Base
	validates :plate , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blacklists_controller.rb
class BlacklistsController < ApplicationController
  def index
  	@blacklists = Blacklist.all
  end

  def new
  	@blacklists = Blacklist.new
  end

  def create
  	@blacklists = Blacklist.new(params.require(:blacklist).permit(:platen, :vtype, :comment, :cmodel))
  	if @blacklists.save
  		redirect_to blacklists_path
  	else
  		redirect_to new_blacklist_path
  	end

  end

  def show
  	@blacklists = Blacklist.find(params[:id])
  end

  def edit
  end

  def update
  end

end

app/controllers/plates_controller.rb
class PlatesController < ApplicationController
  before_action :set_plate, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  def detective
    
    @req = JSON.parse(request.body.read)
    
    # data from results 
    
    r = @req["results"][0]
    plate = r["plate"]
    confidence  = r["confidence"]
    processing  = r["processing_time_ms"]
    
    # data from regions_of_interest

    coordinates = r["coordinates"][0]
    x = coordinates["x"]
    y = coordinates["y"]
    
    #general data 
    uuid    =     @req["uuid"]
    camid   =     @req["camera_id"]
    siteid  =     @req["site_id"]

    @ringo = Blacklist.exists?(platen: plate)

    
    @enreg = Plate.new(plate_params)
    @enreg.siteid = siteid
    @enreg.camid = camid
    @enreg.plate = plate
    @enreg.confidence = confidence
    @enreg.process = processing
    @enreg.x = x
    @enreg.y = y
    @enreg.uuid = uuid
    if @ringo 
      @enreg.blacklisted = "true"
    else
      @enreg.blacklisted = "false"
    end
    @enreg.save
    
    render json: "thank you #{plate}, #{confidence}, #{processing}, #{x}, #{y}, #{uuid}, #{camid}, #{siteid} "
    
  end
  # GET /plates
  # GET /plates.json
  def index
    @plates = Plate.all
  end

  # GET /plates/1
  # GET /plates/1.json
  def show
  end

  # GET /plates/new
  def new
    @plate = Plate.new
  end

  # GET /plates/1/edit
  def edit
  end

  # POST /plates
  # POST /plates.json
  def create
    @plate = Plate.new(plate_params)

    respond_to do |format|
      if @plate.save
        format.html { redirect_to @plate, notice: 'Plate was successfully created.' }
        format.json { render :show, status: :created, location: @plate }
      else
        format.html { render :new }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plates/1
  # PATCH/PUT /plates/1.json
  def update
    respond_to do |format|
      if @plate.update(plate_params)
        format.html { redirect_to @plate, notice: 'Plate was successfully updated.' }
        format.json { render :show, status: :ok, location: @plate }
      else
        format.html { render :edit }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plates/1
  # DELETE /plates/1.json
  def destroy
    @plate.destroy
    respond_to do |format|
      format.html { redirect_to plates_url, notice: 'Plate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plate
      @plate = Plate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plate_params
      params.require(:plate).permit(:siteid, :camid, :plate, :confidence, :process, :x, :y, :uuid, :blacklisted)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blacklists_helper.rb
module BlacklistsHelper
end

app/helpers/plates_helper.rb
module PlatesHelper
end

app/views/blacklists/edit.html.erb
<h1>Blacklists#edit</h1>
<p>Find me in app/views/blacklists/edit.html.erb</p>

app/views/blacklists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blacklist listing</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Violation type</th>
      <th>Plate</th>
      <th>Car model</th>
      <th>Created_at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blacklists.each do |blacklist| %>
      <tr>
        <td><%= blacklist.comment %></td>
        <td><%= blacklist.vtype %></td>
        <td><span style="color:#FF0040"><%= blacklist.platen %></td>
        <td><%= blacklist.cmodel %></td>
        <td><%= blacklist.created_at %></td>
        <td><%= link_to 'Show', blacklist %></td>
        <td><%= link_to 'Edit', edit_blacklist_path(blacklist) %></td>
        <td><%= link_to 'Destroy', blacklist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New blacklist', new_blacklist_path %>

app/views/blacklists/new.html.erb
<%= form_for(@blacklists) do |f| %>
  <div class="field">
    <%= f.label :Comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :vtype %><br>
    <%= f.text_field :vtype %>
  </div>
  <div class="field">
    <%= f.label :platen %><br>
    <%= f.text_field :platen %>
  </div>
  <div class="field">
    <%= f.label :cmodel %><br>
    <%= f.text_field :cmodel %>
  </div>
  <%= f.submit %>
  <% end %>

app/views/blacklists/show.html.erb
<h1>Blacklists#show</h1>
<p>Find me in app/views/blacklists/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <div class="title-bar" data-responsive-toggle="main-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="main-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">DJAMEL EDDINE</li>
      <li class="has-form">
  <div class="row collapse">
    <div class="large-8 small-9 columns">
      <input type="text" placeholder="Find Stuff">
    </div>
    <div class="large-4 small-3 columns">
      <a href="#" class="alert button expand">Search</a>
    </div>
  </div>
</li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu" data-responsive-menu="drilldown medium-dropdown">
      <li class="has-submenu">
        <a href="#">Tools</a>
        <ul class="submenu menu vertical" data-submenu>
          <li><a href="<%= new_plate_path %>">New Plate</a></li>
          <li><a href="#">Two</a></li>
          <li><a href="#">Three</a></li>
        </ul>
      </li>
      <li><a href="#">Two</a></li>
      <li><a href="#">Three</a></li>
    </ul>
  </div>
</div>

  <body>

    <%= yield %>

  </body>
</html>

app/views/plates/_form.html.erb
<%= form_for(@plate) do |f| %>
  <% if @plate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plate.errors.count, "error") %> prohibited this plate from being saved:</h2>

      <ul>
      <% @plate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :siteid %><br>
    <%= f.text_field :siteid %>
  </div>
  <div class="field">
    <%= f.label :camid %><br>
    <%= f.text_field :camid %>
  </div>
  <div class="field">
    <%= f.label :plate %><br>
    <%= f.text_field :plate %>
  </div>
  <div class="field">
    <%= f.label :confidence %><br>
    <%= f.text_field :confidence %>
  </div>
  <div class="field">
    <%= f.label :process %><br>
    <%= f.text_field :process %>
  </div>
  <div class="field">
    <%= f.label :x %><br>
    <%= f.text_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br>
    <%= f.text_field :y %>
  </div>
  <div class="field">
    <%= f.label :uuid %><br>
    <%= f.text_field :uuid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plates/edit.html.erb
<h1>Editing Plate</h1>

<%= render 'form' %>

<%= link_to 'Show', @plate %> |
<%= link_to 'Back', plates_path %>

app/views/plates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Plates</h1>

<table>
  <thead>
    <tr>
      <th>Siteid</th>
      <th>Camid</th>
      <th>Plate</th>
      <th>blacklisted</th>
      <th>Process</th>
      <th>X</th>
      <th>Y</th>
      <th>Uuid</th>
      <th>Created_at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plates.each do |plate| %>
      <tr>
        <td><%= plate.siteid %></td>
        <td><%= plate.camid %></td>
        <td><span style="color:#FF0040"><%= plate.plate %></td>
        <td><%= plate.blacklisted %></td>
        <td><%= plate.process %></td>
        <td><%= plate.x %></td>
        <td><%= plate.y %></td>
        <td><%= plate.uuid %></td>
        <td><%= plate.created_at %></td>
        <td><%= link_to 'Show', plate %></td>
        <td><%= link_to 'Edit', edit_plate_path(plate) %></td>
        <td><%= link_to 'Destroy', plate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plate', new_plate_path %>

app/views/plates/new.html.erb
<h1>New Plate</h1>

<%= render 'form' %>

<%= link_to 'Back', plates_path %>

app/views/plates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Siteid:</strong>
  <%= @plate.siteid %>
</p>

<p>
  <strong>Camid:</strong>
  <%= @plate.camid %>
</p>

<p>
  <strong>Plate:</strong>
  <%= @plate.plate %>
</p>

<p>
  <strong>Confidence:</strong>
  <%= @plate.confidence %>
</p>

<p>
  <strong>Process:</strong>
  <%= @plate.process %>
</p>

<p>
  <strong>X:</strong>
  <%= @plate.x %>
</p>

<p>
  <strong>Y:</strong>
  <%= @plate.y %>
</p>

<p>
  <strong>Uuid:</strong>
  <%= image_tag( @plate.uuid, :size => "260x180") %>
</p>

<%= link_to 'Edit', edit_plate_path(@plate) %> |
<%= link_to 'Back', plates_path %>